name: Docker latest image

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'
      - 'docs'
    branches: [ main ]
  workflow_dispatch:

jobs:

  docker-release:
    uses: danubetech/workflows/.github/workflows/docker-latest.yml@1.2.0
    with:
      GLOBAL_IMAGE_NAME: universalresolver/driver-did-key
      GLOBAL_REPO_NAME: docker.io
      PATH_TO_DOCKERFILE: docker/Dockerfile
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      CI_SECRET_READER_PERIODIC_TOKEN: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
      VAULTCA: ${{ secrets.VAULTCA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
